#spring:
#  datasource:
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://localhost:5432/pullm
#    username: postgres
#    password: postgres

spring:
  datasource:
    url: jdbc:h2:mem:pullm
    username: sa
    password: password
    driverClassName: org.h2.Driver