server:
  port: ${PORT}
  error:
    include-message: always

spring:
  datasource:
    url: jdbc:h2:mem:pullm
    username: sa
    password: password
    driverClassName: org.h2.Driver
  liquibase:
    change-log: classpath:liquibase/changelog-master.yml
  h2:
    console:
      enabled: true
      path: /h2-ui

cors:
  allowed-origins: "*"
  allowed-methods: "*"
  allowed-headers: "*"
  exposed-headers: "*"

#logging:
#  level:
#    root: debug