server:
  port: ${PORT:8080}
  error:
    include-message: always

spring:
  datasource:
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://localhost:5432/pullm
#    username: postgres
#    password: postgres
    url: jdbc:h2:mem:pullm
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update

  liquibase:
    change-log: classpath:liquibase/changelog-master.yml
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true

springdoc:
  show-login-endpoint: true

cors:
  allowed-origins: "*"
  allowed-methods: "*"
  allowed-headers: "*"
  exposed-headers: "*"

#logging:
#  level:
#    root: debug