
#spring:
#  datasource:
#    url: jdbc:postgresql://${PROD_DB_HOST}:${PROD_DB_PORT}/${PROD_DB_NAME}
#    username: ${PROD_DB_USERNAME}
#    password: ${PROD_DB_PASSWORD}
#    name: pullm

spring:
  datasource:
    url: jdbc:h2:mem:pullm
    username: sa
    password: password
    driverClassName: org.h2.Driver